# Example 1 - Publish a specific Tableau workbook to Tableau Online/Server
# See README for explanation & walkthrough

name: deploy-to-prod
on:
  workflow_dispatch:
  #push:
   # branches:
    #  - main
    #paths-ignore:
     # - '.github/workflows/**'

jobs:
  publish-to-tableau-server-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      
      # Download and unpackage tabcmd
      - run: sudo wget -O tableau-tabcmd.deb "https://downloads.tableau.com/esdalt/2023.1.3/tableau-tabcmd-2023-1-3_all.deb"
      - run: sudo dpkg-deb -x ./tableau-tabcmd.deb ./tabcmdpackage/

      # Accept Tableau EULA for tabcmd
      - run: ./tabcmdpackage/opt/tableau/tabcmd/bin/tabcmd --accepteula

      # Log in to Tableau Server with tabcmd
      - run: ./tabcmdpackage/opt/tableau/tabcmd/bin/tabcmd login -s "${{ secrets.TABLEAU_URL }}" -u "${{ secrets.TABLEAU_USERNAME }}" -p "${{ secrets.TABLEAU_PASSWORD }}"  --no-certcheck

      # Publish workbook
     # - run: |
          #  ./tabcmdpackage/opt/tableau/tabcmd/bin/tabcmd publish "my-tableau-workbook.twbx" -n "My Tableau Workbook" --project "My Project" --overwrite
